### ISSUE TITLE
How can SunPy support and encourage more solar observing instruments to provide affiliated packages?

### ISSUE THREAD

**Issue by nabobalis** [sunpy/sunpy-frontiers-paper#2]
### Provide a general description of the issue or problem.

We need to address this

**Comment by wtbarnes** [comment]
Laura's suggestion: explicit call out to instrument teams in the conclusion. 

Make this a proactive effort rather than waiting for them to come to us.

Maybe the information is there in the paper, just need to make sure the benefits of the affiliated package system are clear, both in terms of why users would want to play in this ecosystem and why instrument teams would want to buy into it.
